from pathlib import Path

path = Path("app/tasks/handlers.py")
text = path.read_text()

anchor = '''        session.refresh(q_entry)\n        if q_entry.state == "active" and q_entry.tx_phase == "active":\n'''
helper = '''        session.refresh(q_entry)\n        preview_digest = meta.get("preview_digest")\n\n        def ensure_purge_reconciliation_audit(*, result: str, recovery_phase: str, reason: str) -> None:\n            existing = list(session.scalars(\n                select(AuditEvent).where(\n                    AuditEvent.operation == "quarantine_purge",\n                    AuditEvent.result == result,\n                )\n            ))\n            for event in existing:\n                try:\n                    details = json.loads(event.details_json or "{}")\n                except Exception:\n                    continue\n                if (\n                    isinstance(details, dict)\n                    and details.get("plan_id") == plan_id\n                    and details.get("item_id") == item.id\n                    and details.get("quarantine_entry_id") == q_entry_id\n                    and details.get("preview_digest") == preview_digest\n                    and details.get("recovery_phase") == recovery_phase\n                ):\n                    return\n            session.add(AuditEvent(\n                operation="quarantine_purge",\n                path=item.source_path,\n                result=result,\n                details_json=json.dumps({\n                    "plan_id": plan_id,\n                    "item_id": item.id,\n                    "task_id": job_id,\n                    "quarantine_entry_id": q_entry_id,\n                    "preview_digest": preview_digest,\n                    "recovery_phase": recovery_phase,\n                    "reason": reason,\n                }, ensure_ascii=False),\n            ))\n\n        if q_entry.state == "active" and q_entry.tx_phase == "active":\n'''
if text.count(anchor) != 1:
    raise SystemExit(f"expected one purge reconciliation anchor, found {text.count(anchor)}")
text = text.replace(anchor, helper, 1)

post_intent_old = '''        if q_entry.state == "purging" and q_entry.tx_phase == "purging":\n            item.state = "planned"\n            item.reason = None\n            return\n\n        if q_entry.state != "purged" or q_entry.tx_phase != "purged":\n            item.state = "failed"\n            item.reason = (\n                "reconciliation unexpected transactional purge state: "\n                f"state={q_entry.state}, tx_phase={q_entry.tx_phase}"\n            )\n            return\n'''
post_intent_new = '''        if q_entry.state == "purging" and q_entry.tx_phase == "purging":\n            recovery_reason = "reconciled transactional purge after crash in purging state"\n            ensure_purge_reconciliation_audit(\n                result="recovered",\n                recovery_phase="post_intent",\n                reason=recovery_reason,\n            )\n            item.state = "planned"\n            item.reason = None\n            return\n\n        if q_entry.state != "purged" or q_entry.tx_phase != "purged":\n            failure_reason = (\n                "reconciliation unexpected transactional purge state: "\n                f"state={q_entry.state}, tx_phase={q_entry.tx_phase}"\n            )\n            ensure_purge_reconciliation_audit(\n                result="failed",\n                recovery_phase="reconciliation_failed",\n                reason=failure_reason,\n            )\n            item.state = "failed"\n            item.reason = failure_reason\n            return\n'''
if text.count(post_intent_old) != 1:
    raise SystemExit(f"expected one B12 branch block, found {text.count(post_intent_old)}")
text = text.replace(post_intent_old, post_intent_new, 1)
path.write_text(text)
